docs/source/eFeatures.rst
efel/cppcore/LibV5.cpp
efel/tests/test_basic.py

segmentation fault in case stim_end == max(t)

Made a tiny change in steady_state_voltage_stimend to prevent a

---

efel/api.py
efel/tests/test_basic.py

getFeatureValues now raise TypeError if feature name doesn't exist

---

efel/cppcore/LibV1.cpp
efel/cppcore/LibV2.cpp
efel/cppcore/LibV3.cpp
efel/cppcore/LibV5.cpp

I will add the same inline comments as PR 18

clean up warnings, mainly related to unsigned/signed comparisons

---

examples/deap/GranuleCell1/GranuleCellDeap1-scoop.py
examples/deap/GranuleCell1/README

* the file was created by using the nbconvert on the Jupyter
notebook, and then updated to have the necessary identifires in the
correct scope

Added a file and instructions for how to use SCOOP

---

efel/cppcore/cppcore.cpp

* PyList_Append does an incref:
https://github.com/python/cpython/blob/master/Objects/listobject.c#L294
as does Py_BuildValue

Fixed some leaks: douple Py_INCREF on list creation

---

efel/cppcore/cppcore.cpp
efel/tests/test_cppcore.py

* Keeping the interface the same

have getFeatureDouble and getFeatureInt use common code

---

efel/cppcore/DependencyTree.cpp
efel/cppcore/DependencyTree.h
efel/cppcore/FillFptrTable.h
efel/cppcore/Global.h
efel/cppcore/cfeature.cpp
efel/cppcore/cfeature.h
efel/cppcore/mapoperations.cpp
efel/cppcore/mapoperations.h
efel/cppcore/types.h

Name frequently used types

---

efel/cppcore/LibV1.cpp
efel/cppcore/LibV2.cpp
efel/cppcore/LibV3.cpp
efel/cppcore/LibV5.cpp
efel/cppcore/LibV5.h
efel/cppcore/cfeature.cpp
efel/cppcore/mapoperations.cpp

* Also changed 'GErrorStr = GErrorStr +' -> 'GErrorStr +='

remove usage of unnecessary string()

---

efel/cppcore/cfeature.cpp
efel/cppcore/cfeature.h
efel/cppcore/eFELLogger.h
efel/tests/test_cppcore.py

* no longer have to always test to see if we are logging
* not threadsafe or anything, could easily be changed
to have a file per class, instead of having it hardcoded

create a logging class

---

efel/cppcore/LibV1.cpp
efel/cppcore/LibV3.cpp
efel/cppcore/LibV4.cpp
efel/cppcore/LibV5.cpp

* Old idiom was:
```
function()
{
if (retVal) {
return nSize;
}else{
return $something;
}
return -1;
}
Transformed to:
function()
{
if (retVal)
return nSize;
//rest
}
```

Improved code flow for early return due to finding cached value

---

efel/DependencyV5.txt
efel/cppcore/FillFptrTable.cpp
efel/cppcore/LibV5.cpp
efel/cppcore/LibV5.h
efel/cppcore/cfeature.cpp
efel/tests/featurenames.json
efel/tests/test_basic.py
efel/tests/testdata/allfeatures/expectedresults.json

Added version of ohmic_input_resistance based on voltage_base and

---

efel/DependencyV5.txt
efel/api.py
efel/cppcore/FillFptrTable.cpp
efel/cppcore/LibV5.cpp
efel/cppcore/LibV5.h
efel/tests/test_basic.py

restricted to stimulus interval

Add a new parameter strict_stiminterval to allow efeature to be

---

Makefile
efel/cppcore/LibV5.cpp
efel/tests/test_basic.py

Making sure unfinished peak doesn't break Spikecount

---

efel/cppcore/DependencyTree.cpp
efel/cppcore/DependencyTree.h

* remove lots of redundant copying of std::string
* use size_t for string operations
* gives me an almost 4x speedup on initialization, which happens a lot

Faster initialization w/ better string parsing

---

docs/source/tex/efeatures.tex

* remove TeX documentation for functions removed in commit
0290d84db3534c2162b40425fa8a18a691802a2b

remove documentation for removed features

---

efel/api.py

efficient when doing 
help(efel.setThreshold)

add default value for the docs.

---

.travis.yml
tox.ini

This PR separates style checks from the nose-tests.

decoupling the style check and nosetests

---

tox.ini

This should remove the bug from the previous commit.

Force tox to run for py35, py36, py37 and py38.

---

.travis.yml

I accidentally removed some part of .travis.yml. This commit fixes that.

Restored travis before_install and after_success.

---

docs/source/eFeatures.rst

This PR adds all the LibV5 features to the documentation, with the exception of these ones:
Peak indices
AP end indices
Min AHP indices
AP begin indices
Is not stuck
Min AHP values
These were not added, because 
- indices might not correspond to what the user gave eFel, due to the interpolation, 
- is_not_stuck returns either 1 or nothing, and I don't know if this is expected to be used by your average user,
- min_AHP_values is basically the same as AHP_depth_abs
Note that I also added to the documentation the features evaluated at custom locations (dendrites, ais, etc.).
Finally, I noticed that there is no "AP_phaseslope_range" field in efel.api.reset. I wonder if I should add it and, if so, what default value I should input.
I also made a little fix in a feature in LibV5. Please double …

Filled LibV5 documentation & did a few fixes

---

efel/cppcore/LibV5.cpp

`AP_begin_width` returns only values after stimulus start, but not `min_ahp_indices`.
Since we are taking values between `AP_begin_width[i]` and `min_ahp_indices[i]`, we have to make sure to only take into account the `min_ahp_indices` AFTER `stim_start`.
If not, it can cause **segmentation faults** if we provide a trace with spikes before the stimulus start.
This PR solves this issue that was raised in #238

Make sure min_ahp_indices are after stimstart in AP_begin_width

---

.readthedocs.yaml
docs/source/conf.py

* also update copyright date in the doc

Add readthedoc config

---

.github/workflows/build.yml
.github/workflows/keep-alive.yml
.github/workflows/test.yml
README.md
efel/tests/test_basic.py
tox.ini

- tox4 fix
- dropping python3.6 support and wheels
- numpy1.24 fix
- 'keep alive' workflow fix

multiple fixes

---

.github/workflows/build.yml
.github/workflows/test.yml
tox.ini

wheels creation already tested on my local branch

add python3.11 to tests and wheels

---

efel/tests/test_basic.py

remove duplicate test

---

.github/workflows/build.yml

I think the release action could not get the tag environment variable from the previous job, so I put the release action inside the same job as the tag action.

Fix release

---

.readthedocs.yaml
requirements_docs.txt

this should fix the error in readthedocs not finding sphinx_rtd_theme

add requirements_docs.txt for readthedocs

---

docs/.gitignore
docs/source/api.rst

Instead of efel.api, the Python documentation now lists the following.
```
api
io
pyfeatures.pyfeatures
units
settings
```

make sure docstring gets generated for whole python API

---

.readthedocs.yaml
docs/examples_to_rst.sh
docs/source/conf.py
requirements_docs.txt
tox.ini

We also need to tell readthedocs to convert examples to rst before building the docs
- [skip] Unit tests are added to cover the changes (skip if not applicable).
- [skip] The changes are mentioned in the documentation (skip if not applicable).
- [skip] CHANGELOG file is updated (skip if not applicable).

also make readthedocs convert examples for docs

---

docs/source/eFeatures.rst

renamed Voltage features -> Subthreshold features
moved from Python features:
to Spike event features: `spikes_per_burst`, `spikes_per_burst_diff`, `spikes_in_burst1_burst2_diff`, `spikes_in_burst1_burstlast_diff`
to Spike shape features: `initburst_sahp`, `initburst_sahp_ssse`, `initburst_sahp_vb`, `phaseslope_max`
I did not move `depol_block_bool` or `impedance`, because they don't fit in spike-related features, neither in subthreshold features

reorganised efeature documentation

---

efel/pyfeatures/pyfeatures.py

Impedance should return an array, not a float
