BlueBrain/eFEL

efel/cppcore/LibV1.cpp
efel/tests/test_basic.py

Fixed the spikecount feature so that it doesn't return -1 when no spikes. Now a value of '0' is returned in that case. Added unit
tests for spikecount

Fixed the spikecount feature so that it doesn't return -1 when no spikes are present

---

efel/api.py
efel/cppcore/cppcore.cpp
efel/tests/test_cppcore.py

* it is agnostic of the feature type: whether it is a double or an int
* added tests
* this is partly in preparation for 'Support eFeatures written in Python'

Add getFeature that will return feature values

---

efel/cppcore/LibV1.cpp
efel/cppcore/LibV1.h

* Following functions were made non-public   __peak_indices
__ISI_values
__spike_width1
__spike_width2
__rest_voltage_value
__burst_ISI_indices
__burst_mean_freq
__interburst_voltage
__adaptation_index
__time_constant
__voltage_deflection
__ohmic_input_resistance
__maxmin_voltage
__steady_state_voltage
__single_burst_ratio
__AP_width
__adaptation_index2
__ISI_CV
__AHP_depth_abs_slow_indices
__AHP_depth
__AP_amplitude_diff
__AHP_depth_diff

move LibV1 internal implementations into file

---

efel/cppcore/LibV2.cpp
efel/cppcore/LibV2.h

* Following functions were made non-public:
- __AP_begin_indices
- __AP_rise_indices
- __AP_fall_indices
- __AP_end_indices
- __AP_duration
- __AP_rise_time
- __AP_fall_time
- __AP_rise_rate
- __AP_fall_rate
- __fast_AHP
- __AP_amplitude_change
- __AP_duration_change
- __AP_rise_rate_change
- __AP_fall_rate_change
- __fast_AHP_change
- __AP_duration_half_width
- __AP_duration_half_width_change
- __steady_state_hyper
- __amp_drop_first_second
- __amp_drop_first_last
- __amp_drop_second_last
- __max_amp_difference

move LibV2 internal implementations into file

---

efel/cppcore/LibV3.cpp
efel/cppcore/LibV3.h

* Following functions were made non-public
-  __peak_indices
-  __ISI_CV
-  __spike_width1
-  __rest_voltage_value
-  __adaptation_index2
-  __AP_width
-  __AP_begin_indices
-  __AP_rise_indices
-  __AP_fall_indices
-  __AP_end_indices
-  __AP_duration
-  __depolarized_base

move LibV3 internal implementations into file

---

efel/cppcore/LibV4.cpp
efel/cppcore/LibV4.h

* Following functions were made non-public
- __peak_indices

move LibV4 internal implementations into file

---

efel/cppcore/LibV5.cpp
efel/cppcore/LibV5.h

* Following functions were made non-public
- __ISI_log_slope
- __spike_width1
- __AP_begin_indices
- __irregularity_index
- __number_initial_spikes
- __AHP_depth_from_peak
- __AHP_time_from_peak
- __AP_begin_width
- __AP_begin_time
- __AP_begin_voltage
- __voltage_deflection_begin
- __AP_phaseslope

move LibV5 internal implementations into file

---

Makefile
utils/efel_graph_dependency

* parses Dependency.txt style files
* Outputs graphviz, or flat text
* as suggested by feature:
https://github.com/BlueBrain/eFEL/issues/6

Added parsing and output of dependency graph

---

efel/api.py
setup.py

Print a warning when user tries to import efel from inside source

---

Makefile

* this is one of the last numpy's to support python 2.6 and have a wheel

for python 2.6 to use numpy==1.10.0

---

efel/cppcore/LibV1.cpp

just set stimEnd to max time in trace.
The problem I have right now is the following:
```python
traces = [{
'T': time,
'V': voltage,
'stim_start': [t_stim],
'stim_end': [np.max(time)],
}]
traces_results = efel.getFeatureValues(traces, ['maximum_voltage', 'voltage_base'])
```
However, probably because of a rounding error, `np.max(time)` in python is greater than the C++ equivalent `time[time.size() - 1]`. This triggers the following error:
`Stimulus end larger than max time in trace. [stim_end: 10, max time: 9.9999999999999822]`

Don't fail when stimEnd larger than max time in trace

---

efel/tests/test_basic.py

The CPP features and Python features are just appended to each other in the function below.
https://github.com/BlueBrain/eFEL/blob/6a395118e6b3306001878ce08f6aef791ec37f1c/efel/api.py#L177
Their order is not guaranteed to be the same. 
This is one of the reasons why PR https://github.com/BlueBrain/eFEL/pull/165 is failing.
This PR simply puts them into sets and checks if the sets are equal.

use set to check if feature names match

---

efel/cppcore/LibV1.cpp
efel/cppcore/LibV2.cpp
efel/cppcore/LibV3.cpp
efel/cppcore/LibV4.cpp
efel/cppcore/LibV5.cpp
efel/cppcore/mapoperations.cpp
efel/cppcore/mapoperations.h

Simplifies the mapoperations.h by removing the duplicated code.
* setIntVec and setDoubleVec become setVec
* getIntVec and getDoubleVec become getVec
* checkInIntmap and checkInDoubleMap become CheckInMap

C++ Templates for allowing mapoperations methods to work on generic types

---

efel/cppcore/LibV5.h

Add missing <stdexcept> header for std::invalid_argument 

---

.github/workflows/main.yml

When downloading all artifacts using download-artifact@v2, they are automatically put in a folder named after the artifact name. So I had to add a step to move all downloaded files to the dist directory.

Parallelize wheel building.

---

efel/DependencyV5.txt
efel/api.py
efel/cppcore/LibV2.cpp
efel/tests/test_basic.py

Solves #194 
Rise time window can now be changed by setting "rise_start_perc" and "rise_end_perc". Both values should be between 0.0 and 1.0. They are 0.0 and 1.0 by default.
E.g. if rise_start_perc is 0.1, and rise_end_perc is 0.9, it means that the rise time will be computed between the first time the voltage gets above (or equal) 10% of the AP amplitude, and the last time the voltage is below 90% of the AP amplitude.

Added customisable percentages to AP_rise_time.

---

efel/api.py
efel/cppcore/LibV1.cpp
efel/tests/test_basic.py

Solves #201.
Added a sahp start parameter that defines the number of ms after each peak after which AHP_depth_abs_slow starts searching for a minimum between two peaks.
However, #201 also mentions a fast after-hyperpolarization window, but I could not manage to find such a thing in efel. It looks to me like fast AHP does not use any window. If indeed there is no such thing, then this can be merged.

Added sahp_start parameter.

---

.github/workflows/main.yml

The [test on testpypi](https://test.pypi.org/project/efel/#files) succeeded: all wheels have been built.
Switching back to publishing on Pypi.

Publish on Pypi.

---

efel/cppcore/LibV5.cpp

Solves the segmentation fault from AP_peak_upstroke arising in the example code of Issue #215.
The problem was that in some cases, there is a peak indice value lower than the corresponding AP_begin_indice, probably due to an AP_begin_indice not found because below threshold.
This was solved by removing the peak_indices that do not have any lower valued AP_begin_indices.
This 'filtering' is not needed in the similar function AP_down_stroke, since no feature used there is threshold-dependent.

Fix potential seg fault in AP_peak_upstroke

---

efel/cppcore/LibV1.cpp
efel/cppcore/Utils.cpp
efel/cppcore/Utils.h

Should fix time constant for Issue #211.
I found two problems in the time constant algorithm.
1./ The start index was increased by 10 for no apparent reason (Does anyone knows why this was there?). This made the example taken form Issue #211 miss the beginning of the decay.
2./ The error estimator used in the time constant algorithm (average RSS) does not allow comparison between datasets ranging over different scales. But the scale of 'log_v' is very dependent on the 'newx' value. I decided to use the normalized standard deviation as the error estimator (which allows us to compare data at different scales).
The example from Issue #211 gives consistent time constants when using this PR.

Fix time constant in Lib1

---

.github/workflows/main.yml
README.md
docs/source/installation.rst
efel/io.py
setup.py
tox.ini

Remove py27 from github CI
Remove py27 from tox
Remove py27 from Readme and docs
Remove py27 libraries in io.py
Solves Issue #222.
I'll push the 4.0 tag once this PR is approved.

Drop python 2.7 support

---

.github/workflows/main.yml

- Skip musllinux wheels (that are built by default in lastest version of cibuildwheel), because we need scipy to test them, but there are no scipy wheels for this architecture
- Remove the building of manylinux-i686 wheels, as we need numpy to test them, but there are no numpy wheels for this architecture
- Also use python version in workflow yaml as string instead of floats (this would have become a problem when adding python 3.10, as with float, 3.10 would have been converted to 3.1)
Additional note: with the latest update of cibuildwheel, the new default wheel for manylinux is manylinux-2014 (previously, it was manylinux-2010)

Remove musllinux and i686 from wheels building

---

efel/cppcore/LibV5.cpp

`Peak indices` computes the indices where the trace crosses the threshold upward and downward, then uses them to determine the peaks. When the trace begins above threshold, there is one more item in the downward crossing vector that `peak_indices` does not expects.
This makes `efel` return an empty list for `peak_indices`, and thus a `spikecount` of `0`.
This change removes any first value(s) of downward threshold crossing that is below the 1st value of upward threshold crossing.
This fixes Issue #240

Fix peak_indices when trace begin above threshold

---

docs/source/eFeatures.rst
efel/DependencyV5.txt
efel/cppcore/FillFptrTable.cpp
efel/cppcore/LibV1.cpp
efel/cppcore/LibV1.h
efel/tests/DependencyV5_LibV4peakindices.txt
efel/tests/test_basic.py
efel/tests/testdata/allfeatures/expectedresults.json
tox.ini

Added to documentation and added tests to:
- time_constant
- depolarized_base
- AP_duration
- AP_rise_rate
- AP_fall_rate
- fast_AHP
- AP_amplitude_change
- AP_duration_change
- AP_rise_rate_change
- AP_fall_rate_change
- fast_AHP_change
- AP_duration_half_width_change
- steady_state_hyper
- amp_drop_first_second
- amp_drop_first_last
- amp_drop_second_last
- max_amp_difference
- AP_amplitude_diff
- AHP_depth_diff
- mean_AP_amplitude
Removed LibV1:threshold_current, which was unreachable
Fixed depolarized_base, which was always returning none
Fixed time_constant, which returned wrong values for some traces, due to limited bounds in its golden section search algorithm. Solves Issue #255

Add features to documentation, add tests, fix LibV1:time_constant and remove LibV1:threshold_current

---

docs/source/eFeatures.rst
efel/DependencyV5.txt
efel/api.py
efel/cppcore/FillFptrTable.cpp
efel/cppcore/LibV5.cpp
efel/cppcore/LibV5.h
efel/cppcore/cfeature.cpp
efel/tests/featurenames.json
efel/tests/test_basic.py
efel/tests/testdata/allfeatures/expectedresults.json

This new implementation does not assume that every spike belongs to a burst. With it, we know at which peak index each burst begins and ends. This avoids to integrate isolated spikes in bursts. 
It takes into account the first spike.
This new implementation is sensitive to `burst_factor`, so I changed the default value of burst_factor to `2`, in order to avoid removing spikes from bursts, although they should remain in them.
New features use this implementation:  `strict_burst_number`, `strict_burst_mean_freq`, `strict_interburst_voltage`
Also added corresponding tests and doc.
This is a possible solution to Issue #249

Add new burst detection implementation

---

.github/workflows/build.yml
.github/workflows/keep-alive.yml
.github/workflows/test.yml

It looks like ubuntu-latest was upgraded recently from 20.04 to 22.04 and that makes our workflow fail at the Set Up Python step.
This PR solves this by using ubuntu 20.04 instead of latest

replace ubuntu-latest by ubuntu-20.04 in github actions

---

docs/source/eFeatures.rst
efel/cppcore/LibV1.cpp
efel/tests/test_basic.py

We used to search for data between `stim_start` index and spike index for `AP_width` feature for all spike indices. When we had a spike before `stim_start`, this was prone to `Segmentation Fault` error (especially when there was no other spike AFTER stim_start).
I solved this by removing indices of any spikes before `stim_start` in `AP_width`.

Only take into account data after stim_start in AP_width

---

docs/source/eFeatures.rst

In the requested features section, there was a jump in title levels:
```
/docs/source/eFeatures.rst:1720: WARNING: Title level inconsistent:
```
which I fixed by adding some intermediate titles. But there probably are better ones.

Fix doc for requested features

---

docs/source/developers.rst
docs/source/eFeatures.rst
efel/DependencyV5.txt
efel/cppcore/FillFptrTable.cpp
efel/cppcore/LibV1.cpp
efel/cppcore/LibV1.h
efel/cppcore/cfeature.cpp
efel/pyfeatures/pyfeatures.py
efel/tests/featurenames.json
efel/tests/test_basic.py
efel/tests/testdata/allfeatures/expectedresults.json

This feature prevents bias of AHP depth due to spurious effect right after AP, see for example red trace here:

Add AHP_depth_slow feature

---

docs/source/eFeatures.rst
efel/DependencyV5.txt
efel/cppcore/FillFptrTable.cpp
efel/cppcore/LibV5.cpp
efel/cppcore/LibV5.h
efel/cppcore/cfeature.cpp
efel/tests/featurenames.json
efel/tests/test_basic.py
efel/tests/testdata/allfeatures/expectedresults.json

similar to interburst_min_values, but also gives a value after the last burst, even when there is no spike after it.

new feature: postburst_min_values

---

efel/cppcore/LibV5.cpp
efel/tests/test_basic.py

Should fix issues #278 and #279 .
Basically, instead of searching for AP_begin from start index (either stim start index, or min ahp index) to peak index, we do the inverse: we search from peak index to start index. Since in both cases we keep the 1st match we find, the new version is better because we avoid all the 'false positives' we can encounter around stim start time.
So this is more resilient to false positives.
However, let's consider a case where the derivative goes above threshold, then slightly below, then above again.
When using the new version of AP_begin_indices, we would only keep the value when we go above the 2nd time.

fix AP_begin_indices

---

efel/cppcore/LibV5.cpp

This should avoid indexing out of bounds in AP_begin.
The old AP_begin feature would search for an AP_begin after the last spike. I think it does not make much sense, so I removed this last search.
Hopefully this will fix the segfaults we sometimes get during wheel building & testing.

fix AP_begin

---

efel/cppcore/LibV5.cpp

If possible, use stim_start_index - 1 instead of stim_start_index when looking for AP_begin to avoid skipping the first AP_begin for the edge case when it is exactly at stim_start_index.

Edge case: first AP_begin exactly at stim_start

---

docs/source/eFeatures.rst

We use voltage_base from LibV5, not LibV1

fix wrong Lib in docs

---

efel/DependencyV5.txt
efel/cppcore/LibV1.cpp
tests/test_pyfeatures.py

also in tests:
-use ms for time fro current datafile
-remove test_current (not useful since current is interpolated now)
-actually check efel output in test_interpolate_current

interpolate current if present

---

README.md
docs/source/installation.rst
docs/source/python_example1.rst
efel/api.py
examples/basic/basic_example1.py
tests/update_expectedresults.py
tests/update_featurenames.py

* fix links in docs, some download links were outdated e.g. (https://www.python.org/download/releases/)
* remove py2 style print functions or from `__future__ import print_function`
* remove old news from README that says we dropped py26 in 2016 etc. Even py37 is no longer supported today (https://endoflife.date/python). We can perhaps consider having a CHANGELOG file in the future to list the important changes as well as the versions introducing them.

Docs cleanup

---

.github/workflows/build.yml
.github/workflows/keep-alive.yml
.github/workflows/test.yml
.readthedocs.yaml
efel/cppcore/CMakeLists.txt
efel/cppcore/LibV1.cpp
efel/cppcore/LibV2.cpp
efel/cppcore/LibV3.cpp
efel/cppcore/LibV5.cpp
efel/cppcore/cfeature.cpp
efel/cppcore/cfeature.h
efel/cppcore/cppcore.cpp
efel/cppcore/efel.cpp
efel/cppcore/mapoperations.cpp
efel/cppcore/mapoperations.h
tests/test_cppcore.py
tox.ini

Part of https://github.com/BlueBrain/eFEL/issues/321.
Memoization previously was done n_features times hence it was very hard to test.
There are ~150 C++ features. Each was performing a separate checking and retrieval of the cached results. Now there is only one implementation.
The responsibility of memoization is moved to cfeature. It became testable.
Does not introduce behavioural changes.
Scientists writing features (or reading them) do not have to worry about the underlying memoization mechanisms.
Uses C++17 for the `if constexpr (std::is_same_v<T, int>)` that allows conditional compilation of templates.
Note: CI image is updated to become ubuntu-22.04 since it uses gcc-11 by default. Otherwise we have to explicitly install gcc-11in each ci task. This change does not affect the users …

cppcore: implement memoization once for all features

---

efel/cppcore/LibV1.cpp
efel/cppcore/LibV2.cpp
efel/cppcore/LibV3.cpp
efel/cppcore/LibV5.cpp
efel/cppcore/eFELLogger.h
setup.py
tests/test_cppcore.py

Changes:
* fixes linux, windows and mac wheel builds (previously failing)
* replace deprecated bind2nd with lambda
* add destructor to efel logger (to close the file once logger gets out of scope)

bring efel to c++17 standard

---

Makefile
utils/efel_graph_dependency.py

* make it python3 compat
* aesthetics to display by taking less space
* update pygraphviz version

update plotting of dependency_graph

---

efel/cppcore/CMakeLists.txt
efel/cppcore/EfelExceptions.h
efel/cppcore/Utils.h
efel/cppcore/cfeature.cpp
efel/cppcore/cppcore.cpp
tests/test_basic.py
tests/test_cppcore.py

When `exit(1)`  is called within a C++ library that's being used by Python (e.g., through a Python API), it will terminate the entire process. 
This PR replaces the `exit(1)` statements with exception handling. It further translates C++ exceptions to Python's built-in exceptions to enable graceful failures.
Given the frequent use of exit calls throughout eFEL – appearing in over 15 distinct locations, notably within the frequently used LinearInterpolation function – this update is expected to prevent approximately 95% of potential future crashes.
Related to #321 .

replace C++ exit(1) statements with exception handling

---

setup.py

EfelExceptions.h file was added in PR #329 but it was not added to the headers list in setup. Because of this, it was not included in the tarball, and users would not be able to install efel without wheels.
Fixes Issue #332

add EfelExceptions.h to setup

---

.github/workflows/build.yml
.github/workflows/test.yml
tox.ini

Adds CPython3.12 wheel built deployment and testing.
Update actions/setup-python from v2 to v4.

Add Py312 wheel building + testing

---

.github/workflows/build.yml

Removes cp38 from the wheel build since the recent scipy does not support it (and the old scipy does not support cp312).

rm cp38 from wheel build

---

efel/pyfeatures/isi.py

Please include a summary of the change.
By default the change will increment the patch version.
To increment major or minor changes add #major or #minor to the PR description.

ISI_CV: return None when None

---

CHANGELOG.rst
docs/source/eFeatures.rst
examples/sonata-network/sonata-network.ipynb

adding AP_height to documentation
- [ skip] Unit tests are added to cover the changes (skip if not applicable).
- [ skip] The changes are mentioned in the documentation (skip if not applicable).
- [ X ] CHANGELOG file is updated (skip if not applicable).

adding AP_height to documentation

---

.github/workflows/build-wheels.yml
.github/workflows/test.yml
docs/source/eFeatures.rst
docs/source/python_examples.rst
examples/nmc-portal/L5TTPC2.ipynb
requirements_docs.txt
tox.ini

python efeature was not linked for a particular feature in the documentation
- [skip ] Unit tests are added to cover the changes (skip if not applicable).
- [skip ] The changes are mentioned in the documentation (skip if not applicable).
- [ skip] CHANGELOG file is updated (skip if not applicable).

small fix in documentation

---

.readthedocs.yaml

fix in readthedocs.yml

---

.gitignore
.readthedocs.yaml
docs/examples_to_rst.sh
examples_to_rst.sh
tox.ini

@anilbey it looks like we cannot use `cd` in readthedocs, so I had to copy back the rst converting code to `.readthedocs.yml ` with updated paths.

Readthedocs

---

CHANGELOG.rst
docs/source/eFeatures.rst

Add an explanation about interpolation, time, voltage and current in the docs.

Improved docs

---

README.md
efel/api.py
examples/basic/basic_example1.py

- Add `set_setting` example in quickstart
- Fix issue #366

docs: add set_setting example in quickstart and fix issue #366

---

CHANGELOG.rst
efel/cppcore/SpikeShape.cpp
tests/test_basic.py

Fixes issue #396 .
Since refactoring in PR #334, a feature is not computed when one of its dependency cannot be resolved. This however raised a new edge case: When there is only one spike, and the `min_AHP_indices` is empty / `None` (when the only value would be at `stim_end`, and is thus removed), then one dependency is empty, but the feature could still be computed. To make the feature compute nonetheless in this case, we can catch the 'dependency is None' error before the feature computation stage.

fix edge case in AP_begin_indices

---

CHANGELOG.rst
efel/pyfeatures/pyfeatures.py
tests/test_pyfeatures.py

We change the indexing of smooth_Z, but forget to also change the indexing of freq when applying a smooth_Z index. This should solve the impedance = 0.0 results that we were getting.

fix impedance freq indexing

---

.github/workflows/mirror-ebrains.yml

Updating to use latest access token. We suspect the previous one has expired on ebrains gitlab side.

updating ebrains access token secret in workflow
